name: Azure Static Web Apps CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
    paths-ignore:
      - 'OpenGym/**'
      - '.github/workflows/azure-static-web-app-build-deploy.yml'
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy SWA Job
    steps:
      - run: 'echo "No build required"'
